### ISSUE TITLE
Cert based auth not supported

### ISSUE THREAD

**Issue by jakehilton** [caosiyang/py-mongo-sync#10]
I noticed you support username/password authentication. I would assume it would be trivial to add cert based auth since pymongo supports that natively?

`c = pymongo.MongoClient('mongo-name.example.com',
                        authMechanism='MONGODB-X509',
                        ssl_certfile='/path/to/mongossl/user-cert.pem',
                        ssl_ca_certs='/path/to/mongossl/root-ca.pem')`

Very promising project!

Thanks!

**Comment by caosiyang** [comment]
You're right. It is simple to add the config items of certificates and initialize the connection with them.
I have never used the  X509 certificate and have little knowledge about it, so it is missing.
