### ISSUE TITLE
Print warnings in Python 3

### ISSUE THREAD

**Issue by claflico** [caosiyang/py-mongo-sync#13]
Trying to work with this inside a python docker container built from python:3.6.6-alpine3.7 and I get error messages about the printf lines not being in parenthesis. 

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Terminated, conflict command options found")?
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('invalid direction for', index_items['key'])?

Using the python 2 image python:2.7.15-alpine3.7 worked.

**Comment by caosiyang** [comment]
It was written in Python 2.6,  so  it could run with Python 2.7 but Python 3.
