### ISSUE TITLE
AttributeError when running check command

### ISSUE THREAD

**Issue by claflico** [caosiyang/py-mongo-sync#14]
Using both actual servers and the example in a closed issue I'm getting the following:

`python check.py --from 172.16.10.115:27021 --src-authdb admin --src-username admin --src-password admin --to 172.16.10.116:270
21 --dst-authdb admin --dst-username admin --dst-password admin --src-db test --dst-db test`

Traceback (most recent call last):
  File "check.py", line 24, in <module>
    conf = CheckCommandOptions.parse()
  File "/opt/py-mongo-sync/mongosync/command_options.py", line 90, in parse
    conf.src_hostportstr = args['from']
AttributeError: can't set attribute

**Comment by caosiyang** [comment]
Sorry, I updated the sync tool, but the check tool was not modified, so it reports errors.
NOT USE IT !
