### ISSUE TITLE
mongodb3.6 change stream 

### ISSUE THREAD

**Issue by heroWang** [caosiyang/py-mongo-sync#26]
请问 是否考虑适配 change stream. 以及最关心的, 你有没有调研过change stream对于moveChunk过程中产生的oplog是否也遵循时序,可以用来replay?

**Comment by caosiyang** [comment]
3.6和4.0我这边还未使用，暂时没有适配change stream的计划，以后应该会对change stream做一些调研，毕竟要跟进版本。
