### ISSUE TITLE
考虑支持python3吗？

### ISSUE THREAD

**Issue by ppd0705** [caosiyang/py-mongo-sync#28]
如题
另外我可以在这基础上新建一个仓库开发python3的版本吗？

**Comment by caosiyang** [comment]
python3大势所趋，只是我没有精力去做这个事。

> 另外我可以在这基础上新建一个仓库开发python3的版本吗？

当然可以啊！

**Comment by ppd0705** [comment]
好的，我fork了一份改造成python3啦
谢谢！

**Comment by caosiyang** [comment]
加油加油！
