### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by supersujj** [caosiyang/py-mongo-sync#6]
python check.py --from 172.16.10.115:27021 --src-authdb admin --src-username admin --src-password admin --to 172.16.10.116:27021 --dst-authdb admin --dst-username admin --dst-password admin --dbs test --src-db test --dst-db test　

Terminated, conflict command options found

**Comment by caosiyang** [comment]
Option '--dbs' is conflict with '--src-db' and '--dst-db'.
You could use either of "--dbs test"  and "--src-db test --dst-db test", but not both.

**Comment by supersujj** [comment]
i am sorry, i see it not careful, i change the topic，i  want to know how can incremental sync?
