### ISSUE TITLE
Errors when sync-ing data from one configsvr to another

### ISSUE THREAD

**Issue by cdyw** [caosiyang/py-mongo-sync#9]
Thanks for you code. It work well for between usual replsets. But when I sync data from one config server to another, below error occurs:

pymongo.errors.OperationFailure: w:'majority' is the only valid write concern when writing to config servers, got: { w: 1, wtimeout: 0 }

Then I execute below configuration:

cfg = rs.conf()
cfg.settings.getLastErrorDefaults = { w: "majority", wtimeout: 5000 }
rs.reconfig(cfg)

The error still exists.

**Comment by caosiyang** [comment]
Configdb uses 'majority' as default write concern to guarantees consistency of cluster meta data. Py-mongo-sync uses '1' as default write concern. It is hard code and cannot be configured. You could try to raise the write concern in source code, e.g. raise to 2 or 3 to meet the majority of configdb rs.

> py-mongo-sync/mongosync/mongo_synchronizer.py 
> **w=1**
```
        # init src mongo client
        self._src_mc = mongo_helper.mongo_connect(
                self._src_host,
                self._src_port,
                authdb=self._src_authdb,
                username=self._src_username,
                password=self._src_password,
                w=1)

        # init dst mongo client
        self._dst_mc = mongo_helper.mongo_connect(
                self._dst_host,
                self._dst_port,
                authdb=self._dst_authdb,
                username=self._dst_username,
                password=self._dst_password,
                w=1)
```
